name: build
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
        - wallaby
        - xena
        - yoga
    steps:
    - name: Install QEMU static binaries
      uses: docker/setup-qemu-action@v2
    - name: Configure Buildkit
      uses: docker/setup-buildx-action@v2
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup environment variables
      run: echo PROJECT_REF=$(cat manifest.yml | yq ".${{ matrix.release }}.sha") >> $GITHUB_ENV
    - name: Authenticate with Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}
    - name: Build image
      uses: docker/build-push-action@v3
      with:
        context: .
        cache-from: type=gha,scope=${{ matrix.release }}
        cache-to: type=gha,mode=max,scope=${{ matrix.release }}
        platforms: linux/amd64
        push: true
        build-args: |
          RELEASE=${{ matrix.release }}
          PROJECT=cinder
          PROJECT_REF=${{ env.PROJECT_REF }}
          PROFILES=ceph qemu
          DIST_PACKAGES=
          PIP_PACKAGES=
        tags: |
          quay.io/vexxhost/cinder:${{ env.PROJECT_REF }}
    - name: Promote image
      uses: akhilerm/tag-push-action@v2
      if: github.ref == 'refs/heads/main'
      with:
        src: quay.io/vexxhost/cinder:${{ env.PROJECT_REF }}
        dst: |
          quay.io/vexxhost/cinder:${{ matrix.release }}
