name: build

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release:
          - wallaby
          - xena
          - yoga
    steps:
      - name: Install QEMU static binaries
        uses: docker/setup-qemu-action@v2.0.0

      - name: Configure Buildkit
        uses: docker/setup-buildx-action@v2.0.0

      - name: Checkout project
        uses: actions/checkout@v3.0.2

      - name: Setup environment variables
        run: echo PROJECT_REF=$(cat manifest.yml | yq ".${{ matrix.release }}.sha") >> $GITHUB_ENV

      - name: Authenticate with Quay.io
        uses: docker/login-action@v2.0.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          cache-from: type=gha,scope=${{ matrix.release }}
          cache-to: type=gha,mode=max,scope=${{ matrix.release }}
          platforms: linux/amd64
          push: true
          build-args: |
            RELEASE=${{ matrix.release }}
            PROJECT=cinder
            PROJECT_REF=${{ env.PROJECT_REF }}
            PROFILES=ceph qemu
            DIST_PACKAGES=
            PIP_PACKAGES=os-brick python-cinderclient
          tags: |
            quay.io/vexxhost/cinder:${{ env.PROJECT_REF }}
